name: ultimate_solution_flutter_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.2
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.4.4

  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # Networking
  dio: ^5.4.2
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^6.0.1

  # Local Storage
  sqflite: ^2.3.2
  path_provider: ^2.1.3
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # Localization
  easy_localization: ^3.0.5

  # Dependency Injection
  get_it: ^7.6.7

  # Others
  intl: ^0.19.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/translations/en-US.json
    - assets/translations/ar-EG.json
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

