class StringsConstants {
  static String welcomeBack="welcomeBack";
  static String logBack="logBack";
  static String userId="userId";
  static String password="password";
  static String showMore="showMore";
  static String logIn="logIn";
  static String chooseLanguage="chooseLanguage";
  static String apply="apply";
  static String arabic="arabic";
  static String english="english";
  static String others="others";
  static String noOrdersTitle="noOrdersTitle";
  static String noOrdersSubTitle="noOrdersSubTitle";
  static String status="status";
  static String totalPrice="totalPrice";
  static String date="date";
  static String orderDetails="orderDetails";
  static String delivering="delivering";
  static String returned="returned";
  static String delivered="delivered";
  static String newItems="newItems";
}
